django/myFirstDjango/myfirstDjango/link/urls.py
from django.urls import path
from .views import first, second, third

app_name="link"
urlpatterns = [
        path('first', first, name="first"),
        path('second', second, name="second"),
        path('third', third, name="third"),
]

django/myFirstDjango/myfirstDjango/myfirstDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.views import main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',main),
    path('link/', include('link.urls')),
    path('posts/', include('posts.urls')),
]

django/myFirstDjango/myfirstDjango/posts/urls.py
from django.urls import path
from .views import new, create, show, edit, update, delete

app_name = "posts"
urlpatterns = [
        path('new/', new , name="new"),
        path('create/', create, name="create"),
        path('<int:post_id>/', show, name="show"),
        path('edit/<int:post_id>/',edit, name="edit"),
        path('update/<int:post_id>/', update, name="update"),
        path('delete/<int:post_id>/', delete, name="delete"),
]

django/myFirstDjango/myfirstDjango/link/models.py
from django.db import models

# Create your models here.

django/myFirstDjango/myfirstDjango/posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length = 200)
    content = models.TextField()
    view_count = models.IntegerField(default = 0)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
# Create your models here.

django/myFirstDjango/myfirstDjango/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        labels = {
                'title': '제목',
                'content': '내용'
        }
        widgets = {
                'title': forms.TextInput(attrs={
                    'class': 'form-control'
                    }),
                'content': forms.Textarea(attrs={
                    'class': 'form-control'
                    }),
        }

django/myFirstDjango/myfirstDjango/link/views.py
from django.shortcuts import render

def first(request):
    return render(request, 'link/first.html')


def second(request):
    return render(request, 'link/second.html')


def third(request):
    return render(request, 'link/third.html')
# Create your views here.

django/myFirstDjango/myfirstDjango/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
import pdb

def main(request):
    context = {
        'posts': Post.objects.order_by('-created_at')
    }
    return render(request, 'posts/main.html', context)


def new(request):
    """
    form = PostForm()
    context = {
            'form': form
    }
    """
    context = {
            'form': PostForm()
    }

    return render(request, 'posts/new.html', context)


def create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
        """
        방법1
        title = request.POST.get('title')
        content = request.POST.get('content')
        Post(title=title, content=content).save()

        방법2
        title = request.POST.get('title')
        content = request.POST.get('content')
        Post.objects.create(title=title, content=content)
        """
        return redirect(main)

def show(request, post_id):
    post = Post.objects.get(pk=post_id)
    context = {
        'post': post
    }
    return render(request, 'posts/show.html', context)

def edit(request, post_id):
    post = Post.objects.get(pk=post_id)
    context = {
        'post': post,
        'form': PostForm(instance=post)
    }
    return render(request, 'posts/edit.html', context)

def update(request, post_id):
    if request.method == "POST":
        post = Post.objects.get(pk=post_id)
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts:show', post_id)

def delete(request, post_id):
    if request.method == "POST":
        post = Post.objects.get(pk=post_id)
        post.delete()
        return redirect(main)
# Create your views here.

django/myFirstDjango/myfirstDjango/link/templates/link/first.html
{% extends 'base.html' %}
{% block content %}
{% include 'share/_navbar.html' %}
<h1>
	first
</h1>
{% endblock %}

django/myFirstDjango/myfirstDjango/link/templates/link/second.html
{% extends 'base.html' %}
{% block content %}
<h1>
	        second
</h1>
{% endblock %}

django/myFirstDjango/myfirstDjango/link/templates/link/third.html
{% extends 'base.html' %}
{% block content %}
<h1>
	        third
</h1>
{% endblock %}

django/myFirstDjango/myfirstDjango/myfirstDjango/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
	  <!-- Required meta tags -->
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	  <!-- Bootstrap CSS -->
	  <link rel="stylesheet" href="{% static 'css/base.css?ver=2' %}">
	  <title>My First Django</title>
	</head>
	<body>
	  {% include 'share/_navbar.html' %}
	  {% block content %}
	  {% endblock %}
	  <!-- Optional JavaScript -->
	  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	</body>
</html>

django/myFirstDjango/myfirstDjango/myfirstDjango/templates/share/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="#">Navbar</a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="navbar-toggler-icon"></span>
			  </button>
			    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				        <div class="navbar-nav">
						      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
						      <a class="nav-item nav-link" href="{% url 'posts:new' %}">새 글쓰기</a>
							          <a class="nav-item nav-link" href="#">Pricing</a>
								        <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
									    </div>
									      </div>
</nav>

django/myFirstDjango/myfirstDjango/posts/templates/posts/_form.html
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="{{ btn_value }}" class="btn">

django/myFirstDjango/myfirstDjango/posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block content %}
<h1>
  글 수정하기
</h1>
<form action="{% url 'posts:update' post.id %}" method="post">
  {% include 'posts/_form.html' with form=form btn_value="글 수정" %}
</form>
{% endblock %}

django/myFirstDjango/myfirstDjango/posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
	<h1>
		정훈's blog
	</h1>
	{% for post in posts %}
	<div class="col-md-5 col-12">
		<div class="card" style="width: 18rem; margin-top: 20px;">
			<div class="card-body">
				<h5 class="card-title">{{ post.title }}</h5>
				<p class="card-text">{{ post.content }}</p>
				<p>{{ post.created_at}}</p>
				<a href="{% url 'posts:show' post.id %}" class="btn btn-primary">Go somewhere</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

django/myFirstDjango/myfirstDjango/posts/templates/posts/new.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<h1>
		새로운 글 작성하기
	</h1>
	<form action="{% url 'posts:create' %}" method="POST">
		{% include 'posts/_form.html' with form=form btn_value="글 생성" %}
	  <div class="form-group">
		  <label>글 제목</label>
		  <input type="text" class="form-control" name="title">
	  </div>
	  <div class="form-group">
		  <label>글 내용</label>
		  <textarea class="form-control" name="content"></textarea>
	  </div>

	 <input type="submit" value="글 작성" class="btn btn-outline-primary">
	</form>
</div>
{% endblock %}

django/myFirstDjango/myfirstDjango/posts/templates/posts/show.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>
    게시글 상세 페이지 입니다.
  </h1>

  <h2>
    제목 : {{ post.title }}
  </h2>
  <p>
    내용 : {{ post.content }}
  </p>
  <a href="{% url 'posts:edit' post.id %}" class="btn">수정하기</a>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      삭제하기
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form  action="{% url 'posts:delete' post.id %}" method="POST">
              {% csrf_token %}
              <input type="submit" value="삭제" class="btn">
            </form>
          </div>
        </div>
      </div>
    </div>


</div>
{% endblock %}